"""initial_schema

Revision ID: a5836e42c97a
Revises: 
Create Date: 2026-03-03 18:26:50.047088

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a5836e42c97a'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('coat_colors',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('coat_lengths',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('coat_patterns',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=True),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('google_id', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_index('idx_users_email', 'users', ['email'], unique=True)
    op.create_index('idx_users_google_id', 'users', ['google_id'], unique=True, postgresql_where='google_id IS NOT NULL')
    op.create_table('cat_breeds',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('coat_color_id', sa.UUID(), nullable=False),
    sa.Column('coat_pattern_id', sa.UUID(), nullable=False),
    sa.Column('coat_length_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['coat_color_id'], ['coat_colors.id'], ),
    sa.ForeignKeyConstraint(['coat_length_id'], ['coat_lengths.id'], ),
    sa.ForeignKeyConstraint(['coat_pattern_id'], ['coat_patterns.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_cat_breeds_coat_color', 'cat_breeds', ['coat_color_id'], unique=False)
    op.create_index('idx_cat_breeds_coat_length', 'cat_breeds', ['coat_length_id'], unique=False)
    op.create_index('idx_cat_breeds_coat_pattern', 'cat_breeds', ['coat_pattern_id'], unique=False)
    op.create_table('quiz_sessions',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('source', sa.String(length=10), nullable=False),
    sa.Column('total_questions', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=10), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("source IN ('quiz', 'today')", name='ck_quiz_sessions_source'),
    sa.CheckConstraint("status IN ('active', 'completed')", name='ck_quiz_sessions_status'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_quiz_sessions_user', 'quiz_sessions', ['user_id', 'started_at'], unique=False)
    op.create_table('cat_photos',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('cat_breed_id', sa.UUID(), nullable=False),
    sa.Column('photo_url', sa.String(length=500), nullable=False),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['cat_breed_id'], ['cat_breeds.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_cat_photos_breed', 'cat_photos', ['cat_breed_id', 'display_order'], unique=False)
    op.create_table('correct_answers',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('cat_breed_id', sa.UUID(), nullable=False),
    sa.Column('first_correct_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['cat_breed_id'], ['cat_breeds.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'cat_breed_id', name='uq_correct_answers')
    )
    op.create_index('idx_correct_answers_user', 'correct_answers', ['user_id'], unique=False)
    op.create_table('quiz_questions',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('question_number', sa.Integer(), nullable=False),
    sa.Column('question_type', sa.String(length=20), nullable=False),
    sa.Column('correct_cat_breed_id', sa.UUID(), nullable=False),
    sa.CheckConstraint("question_type IN ('photo_to_name', 'name_to_photo')", name='ck_quiz_questions_type'),
    sa.ForeignKeyConstraint(['correct_cat_breed_id'], ['cat_breeds.id'], ),
    sa.ForeignKeyConstraint(['session_id'], ['quiz_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('session_id', 'question_number', name='uq_quiz_questions')
    )
    op.create_table('session_results',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('source', sa.String(length=10), nullable=False),
    sa.Column('correct_count', sa.Integer(), nullable=False),
    sa.Column('incorrect_count', sa.Integer(), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("source IN ('quiz', 'today')", name='ck_session_results_source'),
    sa.CheckConstraint('correct_count >= 0', name='ck_session_results_correct'),
    sa.CheckConstraint('incorrect_count >= 0', name='ck_session_results_incorrect'),
    sa.ForeignKeyConstraint(['session_id'], ['quiz_sessions.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('session_id', name='uq_session_results')
    )
    op.create_index('idx_session_results_user', 'session_results', ['user_id', 'source', 'completed_at'], unique=False)
    op.create_table('similar_cats',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('cat_breed_id', sa.UUID(), nullable=False),
    sa.Column('similar_cat_breed_id', sa.UUID(), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.CheckConstraint('cat_breed_id <> similar_cat_breed_id', name='ck_similar_cats_no_self'),
    sa.ForeignKeyConstraint(['cat_breed_id'], ['cat_breeds.id'], ),
    sa.ForeignKeyConstraint(['similar_cat_breed_id'], ['cat_breeds.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cat_breed_id', 'similar_cat_breed_id', name='uq_similar_cats')
    )
    op.create_index('idx_similar_cats_breed', 'similar_cats', ['cat_breed_id', 'priority'], unique=False)
    op.create_table('wrong_answers',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('cat_breed_id', sa.UUID(), nullable=False),
    sa.Column('wrong_count', sa.Integer(), nullable=False),
    sa.Column('last_wrong_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('wrong_count >= 1', name='ck_wrong_answers_count'),
    sa.ForeignKeyConstraint(['cat_breed_id'], ['cat_breeds.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'cat_breed_id', name='uq_wrong_answers')
    )
    op.create_index('idx_wrong_answers_user', 'wrong_answers', ['user_id', 'wrong_count', 'last_wrong_at'], unique=False)
    op.create_table('quiz_answers',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('question_number', sa.Integer(), nullable=False),
    sa.Column('selected_cat_breed_id', sa.UUID(), nullable=False),
    sa.Column('is_correct', sa.Boolean(), nullable=False),
    sa.Column('answered_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['selected_cat_breed_id'], ['cat_breeds.id'], ),
    sa.ForeignKeyConstraint(['session_id', 'question_number'], ['quiz_questions.session_id', 'quiz_questions.question_number'], name='fk_quiz_answers_question', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['session_id'], ['quiz_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('session_id', 'question_number', name='uq_quiz_answers')
    )
    op.create_table('quiz_choices',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('question_id', sa.UUID(), nullable=False),
    sa.Column('choice_order', sa.Integer(), nullable=False),
    sa.Column('cat_breed_id', sa.UUID(), nullable=False),
    sa.Column('photo_url', sa.String(length=500), nullable=True),
    sa.ForeignKeyConstraint(['cat_breed_id'], ['cat_breeds.id'], ),
    sa.ForeignKeyConstraint(['question_id'], ['quiz_questions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('question_id', 'cat_breed_id', name='uq_quiz_choices_breed'),
    sa.UniqueConstraint('question_id', 'choice_order', name='uq_quiz_choices_order')
    )
    # similar_cats の対称性保証トリガー
    op.execute("""
        CREATE OR REPLACE FUNCTION fn_similar_cats_mirror()
        RETURNS TRIGGER AS $$
        BEGIN
            INSERT INTO similar_cats (cat_breed_id, similar_cat_breed_id, priority)
            VALUES (NEW.similar_cat_breed_id, NEW.cat_breed_id, NEW.priority)
            ON CONFLICT (cat_breed_id, similar_cat_breed_id) DO NOTHING;
            RETURN NEW;
        END;
        $$ LANGUAGE plpgsql;
    """)
    op.execute("""
        CREATE TRIGGER trg_similar_cats_mirror
        AFTER INSERT ON similar_cats
        FOR EACH ROW EXECUTE FUNCTION fn_similar_cats_mirror();
    """)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("DROP TRIGGER IF EXISTS trg_similar_cats_mirror ON similar_cats")
    op.execute("DROP FUNCTION IF EXISTS fn_similar_cats_mirror")
    op.drop_table('quiz_choices')
    op.drop_table('quiz_answers')
    op.drop_index('idx_wrong_answers_user', table_name='wrong_answers')
    op.drop_table('wrong_answers')
    op.drop_index('idx_similar_cats_breed', table_name='similar_cats')
    op.drop_table('similar_cats')
    op.drop_index('idx_session_results_user', table_name='session_results')
    op.drop_table('session_results')
    op.drop_table('quiz_questions')
    op.drop_index('idx_correct_answers_user', table_name='correct_answers')
    op.drop_table('correct_answers')
    op.drop_index('idx_cat_photos_breed', table_name='cat_photos')
    op.drop_table('cat_photos')
    op.drop_index('idx_quiz_sessions_user', table_name='quiz_sessions')
    op.drop_table('quiz_sessions')
    op.drop_index('idx_cat_breeds_coat_pattern', table_name='cat_breeds')
    op.drop_index('idx_cat_breeds_coat_length', table_name='cat_breeds')
    op.drop_index('idx_cat_breeds_coat_color', table_name='cat_breeds')
    op.drop_table('cat_breeds')
    op.drop_index('idx_users_google_id', table_name='users', postgresql_where='google_id IS NOT NULL')
    op.drop_index('idx_users_email', table_name='users')
    op.drop_table('users')
    op.drop_table('coat_patterns')
    op.drop_table('coat_lengths')
    op.drop_table('coat_colors')
    # ### end Alembic commands ###
